version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/python-app"
    schedule:
      interval: weekly

  - package-ecosystem: "gomod"
    directory: "/go-app"
    schedule:
      interval: weekly

  - package-ecosystem: "cargo"
    directory: "/rust-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "docker"
    directory: "/python-app"
    schedule:
      interval: weekly

  - package-ecosystem: "docker"
    directory: "/go-app"
    schedule:
      interval: weekly

  - package-ecosystem: "docker"
    directory: "/rust-app"
    schedule:
      interval: weekly
