apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod-debugging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pod-debugging
  template:
    metadata:
      labels:
        app: test-pod-debugging
    spec:
      containers:
        - name: test-pod-debugging
          image: ghcr.io/emanuelef/test-pod-debugging:latest
          ports:
            - containerPort: 8080
          env:
            - name: SECOND_API_HOST
              value: test-pod-debugging-second-service.default.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  name: test-pod-debugging-service
spec:
  selector:
    app: test-pod-debugging
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
