apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-second
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app-second
  template:
    metadata:
      labels:
        app: python-app-second
    spec:
      containers:
        - name: python-app-second
          image: ghcr.io/emanuelef/python-app-second:latest
          ports:
            - containerPort: 8080
          env:
            - name: API_HOST
              value: python-app-service.default.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  name: python-app-second-service
spec:
  selector:
    app: python-app-second
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
