apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod-debugging-second
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pod-debugging-second
  template:
    metadata:
      labels:
        app: test-pod-debugging-second
    spec:
      containers:
        - name: test-pod-debugging-second
          image: ghcr.io/emanuelef/test-pod-debugging-second:latest
          ports:
            - containerPort: 8096
          env:
            - name: API_HOST
              value: test-pod-debugging-service.default.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  name: test-pod-debugging-second-service
spec:
  selector:
    app: test-pod-debugging-second
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
  type: ClusterIP
