apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod-debugging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pod-debugging
  template:
    metadata:
      labels:
        app: test-pod-debugging
    spec:
      containers:
      - name: test-pod-debugging
        image: your-docker-username/my-python-app
        ports:
        - containerPort: 8080
          port: 8082
