apiVersion: v1
kind: Service
metadata:
  name: test-pod-debugging-service
spec:
  selector:
    app: test-pod-debugging
  ports:
    - protocol: TCP
      port: 8098
      targetPort: 8098
  type: LoadBalancer
