[package]
name = "rust-app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "rust-app"
path = "src/main.rs"